import { createContext, useContext, useState, ReactNode } from "react";

type Language = "fr" | "en";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  fr: {
    // Navigation
    "nav.discover": "Découvrir",
    "nav.friends": "Amis",
    "nav.wishlist": "Wishlist",
    "nav.forum": "Forum",
    "nav.profile": "Profil",
    
    // Auth
    "auth.welcome": "Bienvenue !",
    "auth.subtitle": "Le marché privé dédié à votre groupe de jeux de société.",
    "auth.login": "Connexion",
    "auth.signup": "Inscription",
    "auth.email": "Email",
    "auth.password": "Mot de passe",
    "auth.fullName": "Nom complet",
    "auth.loginButton": "Se connecter",
    "auth.signupButton": "S'inscrire",
    "auth.loggingIn": "Connexion...",
    "auth.creatingAccount": "Création...",
    "auth.noAccount": "Pas de compte ?",
    "auth.hasAccount": "Déjà un compte ?",
    "auth.signupNow": "S'inscrire",
    "auth.loginNow": "Se connecter",
    "auth.accountCreated": "Compte créé !",
    "auth.welcomeMessage": "Bienvenue !",
    
    // Discover page
    "discover.filters": "Filtres",
    "discover.all": "Tout",
    "discover.sale": "Vente",
    "discover.trade": "Échange",
    "discover.showcase": "Présentation",
    "discover.noGames": "Aucun jeu trouvé",
    "discover.noGamesDesc": "Soyez le premier à publier une annonce !",
    "discover.publish": "Publier un jeu",
    "discover.distance": "à {distance} km",
    "discover.views": "vues",
    "discover.addToWishlist": "Ajouter à la wishlist",
    "discover.removeFromWishlist": "Retirer de la wishlist",
    
    // Friends & Messages page
    "friends.title": "Amis & Messages",
    "friends.add": "Ajouter",
    "friends.messages": "Messages",
    "friends.games": "Jeux",
    "friends.friends": "Amis",
    "friends.requests": "Demandes",
    "friends.startConversation": "Nouvelle conversation",
    "friends.selectFriend": "Sélectionnez un ami",
    "friends.noFriends": "Vous n'avez pas encore d'amis.",
    "friends.addFriendsHint": "Ajoutez des amis pour voir leurs jeux !",
    "friends.noRequests": "Aucune demande d'ami en attente.",
    "friends.receivedRequests": "Demandes reçues",
    "friends.sentRequests": "Demandes envoyées",
    "friends.pending": "En attente",
    "friends.accept": "Accepter",
    "friends.reject": "Refuser",
    "friends.remove": "Supprimer",
    "friends.message": "Message",
    "friends.searchFriend": "Rechercher un ami...",
    "friends.addFriend": "Ajouter un ami",
    "friends.alreadyFriend": "Ami",
    "friends.requestSent": "Demande envoyée",
    "friends.sendRequest": "Envoyer",
    "friends.noGamesFromFriends": "Aucun jeu de vos amis pour le moment.",
    "friends.addFriendsToSee": "Ajoutez des amis pour voir leurs annonces !",
    
    // Messages
    "messages.conversations": "conversations",
    "messages.conversation": "conversation",
    "messages.new": "Nouvelle",
    "messages.createGroup": "Groupe",
    "messages.noConversations": "Aucune conversation",
    "messages.contactSeller": "Contactez un vendeur ou créez un groupe",
    "messages.newConversation": "Nouvelle conversation",
    "messages.startConversation": "Commencez la conversation !",
    "messages.placeholder": "Écrivez un message...",
    "messages.suspended": "Vous êtes temporairement suspendu...",
    "messages.online": "En ligne",
    "messages.members": "membres",
    "messages.report": "Signaler ce message",
    "messages.bannedUntil": "Compte temporairement suspendu",
    "messages.bannedMessage": "Vous ne pouvez pas envoyer de messages jusqu'à",
    
    // Chat
    "chat.conversationNotFound": "Conversation introuvable",
    "chat.back": "Retour",
    
    // Groups
    "group.settings": "Paramètres du groupe",
    "group.name": "Nom du groupe",
    "group.image": "Image du groupe",
    "group.members": "Membres",
    "group.addMember": "Ajouter",
    "group.leave": "Quitter le groupe",
    "group.joinLink": "Lien d'invitation",
    "group.copyLink": "Copier le lien",
    "group.linkCopied": "Lien copié !",
    "group.create": "Créer un groupe",
    "group.creating": "Création...",
    "group.searchUsers": "Rechercher des utilisateurs...",
    "group.selectedMembers": "Membres sélectionnés",
    
    // Forum
    "forum.title": "Forum",
    "forum.subtitle": "Discutez avec la communauté",
    "forum.new": "Nouveau",
    "forum.all": "Tous",
    "forum.general": "Général",
    "forum.strategy": "Jeux de stratégie",
    "forum.party": "Jeux d'ambiance",
    "forum.family": "Jeux familiaux",
    "forum.trading": "Échanges",
    "forum.help": "Aide",
    "forum.noPosts": "Aucun message pour le moment",
    "forum.beFirst": "Soyez le premier à poster !",
    "forum.createPost": "Créer un message",
    "forum.postTitle": "Titre",
    "forum.postTitlePlaceholder": "Sujet de discussion...",
    "forum.postContent": "Contenu",
    "forum.postContentPlaceholder": "Partagez vos pensées...",
    "forum.category": "Catégorie",
    "forum.publish": "Publier",
    "forum.publishing": "Publication...",
    "forum.replies": "réponses",
    "forum.reply": "réponse",
    "forum.likes": "likes",
    "forum.like": "like",
    "forum.replyPlaceholder": "Votre réponse...",
    "forum.sendReply": "Envoyer",
    "forum.noReplies": "Aucune réponse",
    "forum.beFirstReply": "Soyez le premier à répondre !",
    "forum.postPublished": "Message publié",
    "forum.postPublishedDesc": "Votre message a été publié avec succès",
    "forum.contentNotAllowed": "Contenu non autorisé",
    "forum.inappropriateContent": "Votre message contient du contenu inapproprié",
    "forum.loginRequired": "Connexion requise",
    "forum.loginToLike": "Connectez-vous pour aimer les messages",
    "forum.deleted": "Supprimé",
    "forum.postDeleted": "Votre message a été supprimé avec succès",
    "forum.replyDeleted": "Votre réponse a été supprimée avec succès",
    "forum.deletePost": "Supprimer le message",
    "forum.deletePostConfirm": "Êtes-vous sûr de vouloir supprimer ce message ?",
    "forum.deleteReply": "Supprimer la réponse",
    "forum.deleteReplyConfirm": "Êtes-vous sûr de vouloir supprimer cette réponse ?",
    
    // Reports
    "report.title": "Signaler",
    "report.reason": "Raison du signalement",
    "report.description": "Description (optionnelle)",
    "report.descriptionPlaceholder": "Décrivez le problème...",
    "report.submit": "Signaler",
    "report.submitting": "Envoi...",
    "report.sent": "Signalement envoyé",
    "report.sentDesc": "Merci, nous examinerons ce contenu rapidement",
    "report.spam": "Spam",
    "report.harassment": "Harcèlement",
    "report.inappropriate": "Contenu inapproprié",
    "report.illegal": "Contenu illégal",
    "report.scam": "Arnaque",
    "report.other": "Autre",
    "report.loginRequired": "Connectez-vous pour signaler du contenu",
    "report.alreadyReported": "Vous avez déjà signalé ce message",
    "report.messageInfo": "Ce signalement sera examiné. Les utilisateurs avec trop de signalements seront temporairement bannis.",
    
    // Games
    "game.sale": "Vente",
    "game.trade": "Échange",
    "game.presentation": "Présentation",
    "game.condition": "État",
    "game.players": "Joueurs",
    "game.playtime": "Durée",
    "game.age": "Âge",
    "game.contact": "Contacter",
    "game.contacting": "Contacting...",
    "game.noImage": "Pas d'image",
    "game.owner": "Vendeur",
    "game.cannotContactSelf": "Vous ne pouvez pas vous contacter vous-même",
    
    // Post game modal
    "postGame.title": "Publier un jeu",
    "postGame.gameTitle": "Titre du jeu",
    "postGame.gameTitlePlaceholder": "Ex: Catan",
    "postGame.description": "Description",
    "postGame.descriptionPlaceholder": "Décrivez votre jeu...",
    "postGame.type": "Type d'annonce",
    "postGame.price": "Prix (€)",
    "postGame.condition": "État",
    "postGame.conditionNew": "Neuf",
    "postGame.conditionLikeNew": "Comme neuf",
    "postGame.conditionGood": "Bon état",
    "postGame.conditionUsed": "Usé",
    "postGame.players": "Nombre de joueurs",
    "postGame.playersPlaceholder": "Ex: 2-4",
    "postGame.playtime": "Durée de partie",
    "postGame.playtimePlaceholder": "Ex: 60 min",
    "postGame.age": "Âge minimum",
    "postGame.agePlaceholder": "Ex: 10+",
    "postGame.images": "Photos (max 5)",
    "postGame.addImage": "Ajouter",
    "postGame.publish": "Publier",
    "postGame.publishing": "Publication...",
    
    // Wishlist
    "wishlist.title": "Ma Wishlist",
    "wishlist.subtitle": "Vos jeux favoris",
    "wishlist.empty": "Votre wishlist est vide",
    "wishlist.emptyDesc": "Ajoutez des jeux depuis la page Découvrir",
    "wishlist.discover": "Découvrir des jeux",
    
    // Profile
    "profile.title": "Mon Profil",
    "profile.myGames": "Mes jeux",
    "profile.edit": "Modifier",
    "profile.games": "jeux",
    "profile.friends": "amis",
    "profile.memberSince": "Membre depuis",
    
    // Settings
    "settings.title": "Paramètres",
    "settings.manage": "Gérez votre compte",
    "settings.personalInfo": "Informations personnelles",
    "settings.fullName": "Nom complet",
    "settings.username": "Nom d'utilisateur",
    "settings.email": "Email",
    "settings.emailNote": "L'email ne peut pas être modifié",
    "settings.location": "Localisation",
    "settings.visibleOnMap": "Visible sur la carte",
    "settings.visibleOnMapDesc": "Les autres utilisateurs pourront vous trouver",
    "settings.detectLocation": "Détecter ma position",
    "settings.updateLocation": "Mettre à jour ma position",
    "settings.save": "Sauvegarder les modifications",
    "settings.saving": "Sauvegarde...",
    "settings.preferences": "Préférences",
    "settings.notifications": "Notifications",
    "settings.darkMode": "Mode sombre",
    "settings.language": "Langue",
    "settings.french": "Français",
    "settings.english": "English",
    "settings.info": "Informations",
    "settings.legal": "Mentions légales",
    "settings.privacy": "Politique de confidentialité",
    "settings.help": "Aide et FAQ",
    "settings.signOut": "Se déconnecter",
    
    // Map
    "map.title": "Carte",
    "map.findNearby": "Trouvez des joueurs près de chez vous",
    "map.loading": "Chargement de la carte...",
    
    // Common
    "common.cancel": "Annuler",
    "common.confirm": "Confirmer",
    "common.delete": "Supprimer",
    "common.deleting": "Suppression...",
    "common.loading": "Chargement...",
    "common.error": "Erreur",
    "common.success": "Succès",
    "common.save": "Sauvegarder",
    "common.search": "Rechercher...",
    "common.noResults": "Aucun résultat",
    "common.close": "Fermer",
    "common.back": "Retour",
    "common.next": "Suivant",
    "common.previous": "Précédent",
    "common.yes": "Oui",
    "common.no": "Non",
    
    // Header
    "header.search": "Rechercher...",
    "header.publish": "Publier",
    "header.login": "Connexion",
    "header.settings": "Paramètres",
    "header.profile": "Mon profil",
    "header.legal": "Mentions légales",
    "header.signOut": "Déconnexion",
    
    // Notifications
    "notifications.title": "Notifications",
    "notifications.markAllRead": "Tout marquer comme lu",
    "notifications.empty": "Aucune notification",
    "notifications.emptyDesc": "Vous n'avez pas de nouvelles notifications",
    "notifications.newMessages": "Nouveaux messages",
    "notifications.unreadMessages": "Vous avez {count} message(s) non lu(s)",
    
    // Sell game modal
    "sell.title": "Vendre ce jeu",
    "sell.price": "Prix de vente (€)",
    "sell.buyer": "Acheteur",
    "sell.searchBuyer": "Rechercher un acheteur...",
    "sell.orManual": "Ou entrer manuellement",
    "sell.buyerName": "Nom de l'acheteur",
    "sell.buyerEmail": "Email de l'acheteur",
    "sell.paymentMethod": "Moyen de paiement",
    "sell.stripeInfo": "Le paiement sera effectué via Stripe",
    "sell.createLink": "Créer le lien de paiement",
    "sell.creating": "Création...",

    // Support
    "support.title": "Support",
    "support.subtitle": "Comment pouvons-nous vous aider ?",
  },
  en: {
    // Navigation
    "nav.discover": "Discover",
    "nav.friends": "Friends",
    "nav.wishlist": "Wishlist",
    "nav.forum": "Forum",
    "nav.profile": "Profile",
    
    // Auth
    "auth.welcome": "Welcome!",
    "auth.subtitle": "The private marketplace for your board game group.",
    "auth.login": "Login",
    "auth.signup": "Sign up",
    "auth.email": "Email",
    "auth.password": "Password",
    "auth.fullName": "Full name",
    "auth.loginButton": "Log in",
    "auth.signupButton": "Sign up",
    "auth.loggingIn": "Logging in...",
    "auth.creatingAccount": "Creating...",
    "auth.noAccount": "No account?",
    "auth.hasAccount": "Already have an account?",
    "auth.signupNow": "Sign up",
    "auth.loginNow": "Log in",
    "auth.accountCreated": "Account created!",
    "auth.welcomeMessage": "Welcome!",
    
    // Discover page
    "discover.filters": "Filters",
    "discover.all": "All",
    "discover.sale": "For sale",
    "discover.trade": "Trade",
    "discover.showcase": "Showcase",
    "discover.noGames": "No games found",
    "discover.noGamesDesc": "Be the first to post a listing!",
    "discover.publish": "Publish a game",
    "discover.distance": "{distance} km away",
    "discover.views": "views",
    "discover.addToWishlist": "Add to wishlist",
    "discover.removeFromWishlist": "Remove from wishlist",
    
    // Friends & Messages page
    "friends.title": "Friends & Messages",
    "friends.add": "Add",
    "friends.messages": "Messages",
    "friends.games": "Games",
    "friends.friends": "Friends",
    "friends.requests": "Requests",
    "friends.startConversation": "New conversation",
    "friends.selectFriend": "Select a friend",
    "friends.noFriends": "You don't have any friends yet.",
    "friends.addFriendsHint": "Add friends to see their games!",
    "friends.noRequests": "No pending friend requests.",
    "friends.receivedRequests": "Received requests",
    "friends.sentRequests": "Sent requests",
    "friends.pending": "Pending",
    "friends.accept": "Accept",
    "friends.reject": "Reject",
    "friends.remove": "Remove",
    "friends.message": "Message",
    "friends.searchFriend": "Search for a friend...",
    "friends.addFriend": "Add friend",
    "friends.alreadyFriend": "Friend",
    "friends.requestSent": "Request sent",
    "friends.sendRequest": "Send",
    "friends.noGamesFromFriends": "No games from your friends yet.",
    "friends.addFriendsToSee": "Add friends to see their listings!",
    
    // Messages
    "messages.conversations": "conversations",
    "messages.conversation": "conversation",
    "messages.new": "New",
    "messages.createGroup": "Group",
    "messages.noConversations": "No conversations",
    "messages.contactSeller": "Contact a seller or create a group",
    "messages.newConversation": "New conversation",
    "messages.startConversation": "Start the conversation!",
    "messages.placeholder": "Write a message...",
    "messages.suspended": "You are temporarily suspended...",
    "messages.online": "Online",
    "messages.members": "members",
    "messages.report": "Report this message",
    "messages.bannedUntil": "Account temporarily suspended",
    "messages.bannedMessage": "You cannot send messages until",
    
    // Chat
    "chat.conversationNotFound": "Conversation not found",
    "chat.back": "Back",
    
    // Groups
    "group.settings": "Group settings",
    "group.name": "Group name",
    "group.image": "Group image",
    "group.members": "Members",
    "group.addMember": "Add",
    "group.leave": "Leave group",
    "group.joinLink": "Invite link",
    "group.copyLink": "Copy link",
    "group.linkCopied": "Link copied!",
    "group.create": "Create group",
    "group.creating": "Creating...",
    "group.searchUsers": "Search users...",
    "group.selectedMembers": "Selected members",
    
    // Forum
    "forum.title": "Forum",
    "forum.subtitle": "Discuss with the community",
    "forum.new": "New",
    "forum.all": "All",
    "forum.general": "General",
    "forum.strategy": "Strategy games",
    "forum.party": "Party games",
    "forum.family": "Family games",
    "forum.trading": "Trading",
    "forum.help": "Help",
    "forum.noPosts": "No posts yet",
    "forum.beFirst": "Be the first to post!",
    "forum.createPost": "Create a post",
    "forum.postTitle": "Title",
    "forum.postTitlePlaceholder": "Discussion topic...",
    "forum.postContent": "Content",
    "forum.postContentPlaceholder": "Share your thoughts...",
    "forum.category": "Category",
    "forum.publish": "Publish",
    "forum.publishing": "Publishing...",
    "forum.replies": "replies",
    "forum.reply": "reply",
    "forum.likes": "likes",
    "forum.like": "like",
    "forum.replyPlaceholder": "Your reply...",
    "forum.sendReply": "Send",
    "forum.noReplies": "No replies",
    "forum.beFirstReply": "Be the first to reply!",
    "forum.postPublished": "Post published",
    "forum.postPublishedDesc": "Your post has been published successfully",
    "forum.contentNotAllowed": "Content not allowed",
    "forum.inappropriateContent": "Your message contains inappropriate content",
    "forum.loginRequired": "Login required",
    "forum.loginToLike": "Log in to like posts",
    "forum.deleted": "Deleted",
    "forum.postDeleted": "Your post has been deleted successfully",
    "forum.replyDeleted": "Your reply has been deleted successfully",
    "forum.deletePost": "Delete post",
    "forum.deletePostConfirm": "Are you sure you want to delete this post?",
    "forum.deleteReply": "Delete reply",
    "forum.deleteReplyConfirm": "Are you sure you want to delete this reply?",
    
    // Reports
    "report.title": "Report",
    "report.reason": "Reason for reporting",
    "report.description": "Description (optional)",
    "report.descriptionPlaceholder": "Describe the problem...",
    "report.submit": "Report",
    "report.submitting": "Submitting...",
    "report.sent": "Report sent",
    "report.sentDesc": "Thank you, we will review this content shortly",
    "report.spam": "Spam",
    "report.harassment": "Harassment",
    "report.inappropriate": "Inappropriate content",
    "report.illegal": "Illegal content",
    "report.scam": "Scam",
    "report.other": "Other",
    "report.loginRequired": "Log in to report content",
    "report.alreadyReported": "You have already reported this message",
    "report.messageInfo": "This report will be reviewed. Users with too many reports will be temporarily banned.",
    
    // Games
    "game.sale": "For sale",
    "game.trade": "Trade",
    "game.presentation": "Showcase",
    "game.condition": "Condition",
    "game.players": "Players",
    "game.playtime": "Playtime",
    "game.age": "Age",
    "game.contact": "Contact",
    "game.contacting": "Contacting...",
    "game.noImage": "No image",
    "game.owner": "Seller",
    "game.cannotContactSelf": "You cannot contact yourself",
    
    // Post game modal
    "postGame.title": "Publish a game",
    "postGame.gameTitle": "Game title",
    "postGame.gameTitlePlaceholder": "E.g.: Catan",
    "postGame.description": "Description",
    "postGame.descriptionPlaceholder": "Describe your game...",
    "postGame.type": "Listing type",
    "postGame.price": "Price (€)",
    "postGame.condition": "Condition",
    "postGame.conditionNew": "New",
    "postGame.conditionLikeNew": "Like new",
    "postGame.conditionGood": "Good",
    "postGame.conditionUsed": "Used",
    "postGame.players": "Number of players",
    "postGame.playersPlaceholder": "E.g.: 2-4",
    "postGame.playtime": "Game duration",
    "postGame.playtimePlaceholder": "E.g.: 60 min",
    "postGame.age": "Minimum age",
    "postGame.agePlaceholder": "E.g.: 10+",
    "postGame.images": "Photos (max 5)",
    "postGame.addImage": "Add",
    "postGame.publish": "Publish",
    "postGame.publishing": "Publishing...",
    
    // Wishlist
    "wishlist.title": "My Wishlist",
    "wishlist.subtitle": "Your favorite games",
    "wishlist.empty": "Your wishlist is empty",
    "wishlist.emptyDesc": "Add games from the Discover page",
    "wishlist.discover": "Discover games",
    
    // Profile
    "profile.title": "My Profile",
    "profile.myGames": "My games",
    "profile.edit": "Edit",
    "profile.games": "games",
    "profile.friends": "friends",
    "profile.memberSince": "Member since",
    
    // Settings
    "settings.title": "Settings",
    "settings.manage": "Manage your account",
    "settings.personalInfo": "Personal information",
    "settings.fullName": "Full name",
    "settings.username": "Username",
    "settings.email": "Email",
    "settings.emailNote": "Email cannot be changed",
    "settings.location": "Location",
    "settings.visibleOnMap": "Visible on map",
    "settings.visibleOnMapDesc": "Other users will be able to find you",
    "settings.detectLocation": "Detect my location",
    "settings.updateLocation": "Update my location",
    "settings.save": "Save changes",
    "settings.saving": "Saving...",
    "settings.preferences": "Preferences",
    "settings.notifications": "Notifications",
    "settings.darkMode": "Dark mode",
    "settings.language": "Language",
    "settings.french": "Français",
    "settings.english": "English",
    "settings.info": "Information",
    "settings.legal": "Legal notice",
    "settings.privacy": "Privacy policy",
    "settings.help": "Help & FAQ",
    "settings.signOut": "Sign out",
    
    // Map
    "map.title": "Map",
    "map.findNearby": "Find players near you",
    "map.loading": "Loading map...",
    
    // Common
    "common.cancel": "Cancel",
    "common.confirm": "Confirm",
    "common.delete": "Delete",
    "common.deleting": "Deleting...",
    "common.loading": "Loading...",
    "common.error": "Error",
    "common.success": "Success",
    "common.save": "Save",
    "common.search": "Search...",
    "common.noResults": "No results",
    "common.close": "Close",
    "common.back": "Back",
    "common.next": "Next",
    "common.previous": "Previous",
    "common.yes": "Yes",
    "common.no": "No",
    
    // Header
    "header.search": "Search...",
    "header.publish": "Publish",
    "header.login": "Login",
    "header.settings": "Settings",
    "header.profile": "My profile",
    "header.legal": "Legal notice",
    "header.signOut": "Sign out",
    
    // Notifications
    "notifications.title": "Notifications",
    "notifications.markAllRead": "Mark all as read",
    "notifications.empty": "No notifications",
    "notifications.emptyDesc": "You have no new notifications",
    "notifications.newMessages": "New messages",
    "notifications.unreadMessages": "You have {count} unread message(s)",
    
    // Sell game modal
    "sell.title": "Sell this game",
    "sell.price": "Sale price (€)",
    "sell.buyer": "Buyer",
    "sell.searchBuyer": "Search for a buyer...",
    "sell.orManual": "Or enter manually",
    "sell.buyerName": "Buyer name",
    "sell.buyerEmail": "Buyer email",
    "sell.paymentMethod": "Payment method",
    "sell.stripeInfo": "Payment will be made via Stripe",
    "sell.createLink": "Create payment link",
    "sell.creating": "Creating...",

    // Support
    "support.title": "Support",
    "support.subtitle": "How can we help you?",
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem("app-language");
    return (saved as Language) || "fr";
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem("app-language", lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};
